// src/app/layout.jsx
import { AuthProvider } from "./providers";
import { Geist, Geist_Mono, Noto_Sans_Lao } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const notoSansLao = Noto_Sans_Lao({ variable: "--font-noto-sans-lao", subsets: ["latin"] });

export const metadata = {
  title: "Together We Achieve",
  description: "Generated by together we achieve",
};

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: "no",
};

export default async function RootLayout({ children }) {
  // ✅ Fetch session on the server
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSansLao.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* ✅ Pass session to Client Component */}
        <AuthProvider session={session}>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}